name: タスク
description: 開発タスクを管理するためのフォーム
labels: ["task"]
assignees: ruiy03
  - # ここに自分のGitHubユーザー名を入力
body:
  - type: markdown
    attributes:
      value: |
        新しい開発タスクを作成します。必要な情報を入力してください。
  
  - type: input
    id: task-title
    attributes:
      label: タスク名
      description: このタスクの簡潔なタイトルを入力してください
      placeholder: 例：ログイン機能の実装
    validations:
      required: true
  
  - type: textarea
    id: task-description
    attributes:
      label: タスクの詳細
      description: このタスクの詳細な説明を入力してください
      placeholder: |
        何を実装/修正するか、どのような要件があるかなど...
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: 優先度
      description: このタスクの優先度を選択してください
      options:
        - High（高）
        - Medium（中）- Default
        - Low（低）
      default: 1
    validations:
      required: true
  
  - type: dropdown
    id: category
    attributes:
      label: カテゴリ
      description: このタスクのカテゴリを選択してください
      options:
        - Frontend
        - Backend
        - Database
        - Design
        - Documentation
        - Bug Fix
        - Testing
        - Other
    validations:
      required: true
  
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: 完了条件
      description: このタスクが完了したと判断できる条件を入力してください
      placeholder: |
        - [ ] ○○の機能が正常に動作する
        - [ ] テストケースを作成・実行する
        - [ ] ドキュメントを更新する
    validations:
      required: true
  
  - type: textarea
    id: notes
    attributes:
      label: 補足・メモ
      description: その他の補足情報があれば入力してください
      placeholder: 参考資料のURL、注意点など...
    validations:
      required: false
  
  - type: input
    id: related-issues
    attributes:
      label: 関連Issue
      description: 関連するIssue番号があれば入力してください
      placeholder: 例：#123, #456
    validations:
      required: false
